import { newGenerationPlayer } from './player-model.js';

const SAVE_KEY='the-chairman-save-v1';
const FIRST_TEAM_CAPACITY=25;
const YOUTH_SQUAD_CAPACITY=10;
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const money=n=>`£${Math.round(Number(n)||0).toLocaleString('en-GB')}`;
function readState(){try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null');}catch{return null;}}
function writeState(state){localStorage.setItem(SAVE_KEY,JSON.stringify(state));}
function inject(){const state=readState();if(!state)return;const view=document.querySelector('#view');if(!view)return;injectRetirementNotice(state,view);if(state.activeView==='squad')injectYouthControls(state,view);}
function injectRetirementNotice(state,view){view.querySelector('[data-lifecycle-retirement]')?.remove();const pending=Array.isArray(state.pendingRetirements)?state.pendingRetirements:[];if(!pending.length)return;const p=state.players?.find(x=>x.id===pending[0].id);if(!p)return;const el=document.createElement('section');el.className='card card-pad';el.dataset.lifecycleRetirement='1';el.style.margin='0 0 18px';el.innerHTML=`<div class="section-title"><h2>Retirement decision</h2><span>Chairman's choice</span></div><div class="notice"><strong>${esc(p.name)}</strong> has reached the retirement stage at age ${p.age}. You can try to persuade the player to stay for another year, or confirm retirement.</div><div class="actions" style="margin-top:14px"><button class="btn" data-lifecycle="stay" data-player="${esc(p.id)}">Persuade to stay</button><button class="btn btn-primary" data-lifecycle="retire" data-player="${esc(p.id)}">Confirm retirement</button></div>`;view.prepend(el);}
function injectYouthControls(state,view){const youth=Array.isArray(state.youthSquad)?state.youthSquad:[];const cards=[...view.querySelectorAll('h3')].filter(h=>youth.some(p=>p.name===h.textContent.trim()));cards.forEach(h=>{const p=youth.find(x=>x.name===h.textContent.trim());if(!p||h.closest('[data-youth-enhanced]'))return;const card=h.closest('.card');if(!card)return;card.dataset.youthEnhanced='1';card.querySelectorAll('p').forEach(x=>{if(x.textContent.includes('Promotes to first team at 20'))x.textContent='Youth players remain in the pathway until the manager decides they are ready for senior football.';});const firstTeamAvg=state.players?.length?state.players.reduce((sum,x)=>sum+(Number(x.overall)||0),0)/state.players.length:60;const ready=(Number(p.overall)||0)>=firstTeamAvg-4||(Number(p.development)||0)>=72;const rec=document.createElement('p');rec.className='muted';rec.style.margin='10px 0 0';rec.innerHTML=`Manager recommendation: <strong>${ready?'Ready to be considered for promotion':'Continue development'}</strong>.`;card.appendChild(rec);const actions=document.createElement('div');actions.className='actions';actions.style.marginTop='12px';const btn=document.createElement('button');btn.className=ready?'btn btn-primary':'btn';btn.textContent='Promote to first team';btn.dataset.lifecycle='promote';btn.dataset.player=p.id;btn.disabled=state.players.length>=FIRST_TEAM_CAPACITY;actions.appendChild(btn);card.appendChild(actions);});}
function removePending(state,id){state.pendingRetirements=(state.pendingRetirements||[]).filter(x=>x.id!==id);}
function promoteYouth(id){const state=readState();if(!state)return;const p=(state.youthSquad||[]).find(x=>x.id===id);if(!p)return;if((state.players||[]).length>=FIRST_TEAM_CAPACITY){alert(`The first-team squad is at its ${FIRST_TEAM_CAPACITY}-player capacity.`);return;}state.youthSquad=(state.youthSquad||[]).filter(x=>x.id!==id);state.players=[...(state.players||[]),{...p,retirementPending:false,trainingStatus:'promoted'}];state.news=state.news||[];state.news.unshift({week:state.week,title:`Youth promotion: ${p.name}`,text:`The chairman approved ${p.name} for promotion from the youth pathway.`});writeState(state);location.reload();}
function retirePlayer(id){const state=readState();if(!state)return;const p=(state.players||[]).find(x=>x.id===id);if(!p)return;if((state.youthSquad||[]).length>=YOUTH_SQUAD_CAPACITY){showPromotionRequired(p);return;}completeRetirement(state,p);}
function showPromotionRequired(retiringPlayer){const view=document.querySelector('#view');const existing=view?.querySelector('[data-force-promotion]');existing?.remove();if(!view)return;const youth=readState()?.youthSquad||[];const box=document.createElement('section');box.className='card card-pad';box.dataset.forcePromotion='1';box.style.margin='0 0 18px';box.innerHTML=`<div class="section-title"><h2>Youth pathway is full</h2><span>Promotion required</span></div><div class="notice">You cannot add a new youth player while the youth pathway is full. Promote one youth player first, then ${esc(retiringPlayer.name)} can retire and a new youth player will enter the pathway.</div><div class="list" style="margin-top:12px">${youth.map(p=>`<div class="list-row"><div><strong>${esc(p.name)}</strong><small>${esc(p.position)} · Age ${p.age} · OVR ${p.overall} · Potential ${p.potential}</small></div><button class="btn btn-primary" data-lifecycle="promote" data-player="${esc(p.id)}">Promote</button></div>`).join('')}</div>`;view.prepend(box);}
function completeRetirement(state,p){const retired={...p,retirementPending:false,retiredAtWeek:state.week};state.players=(state.players||[]).filter(x=>x.id!==p.id);state.retiredPlayers=[...(state.retiredPlayers||[]),retired].slice(-30);removePending(state,p.id);const seed=Number(state.week||1)*7919+(state.retiredPlayers.length*37);const youth=newGenerationPlayer(`${state.clubId}-retirement-youth-${state.week}-${state.retiredPlayers.length}`,state.clubId,seed);state.youthSquad=[...(state.youthSquad||[]),youth].slice(0,YOUTH_SQUAD_CAPACITY);state.news=state.news||[];state.news.unshift({week:state.week,title:`Retirement confirmed: ${p.name}`,text:`${p.name} has retired. A new youth player, ${youth.name}, has entered the academy pathway.`});state.inbox=state.inbox||[];state.inbox.unshift({id:Date.now(),type:'RETIREMENT',title:`Retirement completed: ${p.name}`,text:`${p.name} has retired and ${youth.name} has entered the youth pathway.`,unread:true});writeState(state);location.reload();}
function stayPlayer(id){const state=readState();if(!state)return;const p=(state.players||[]).find(x=>x.id===id);if(!p)return;p.retirementPending=false;p.retirementExtensionYears=(p.retirementExtensionYears||0)+1;p.contractYears=Math.max(1,p.contractYears||1);p.morale=Math.min(100,(p.morale||70)+4);removePending(state,id);state.news=state.news||[];state.news.unshift({week:state.week,title:`Player persuaded to stay: ${p.name}`,text:`The chairman convinced ${p.name} to continue for another season.`});state.inbox=state.inbox||[];state.inbox.unshift({id:Date.now(),type:'RETIREMENT',title:`${p.name} stays`,text:`${p.name} agreed to continue for another season after the chairman's intervention.`,unread:true});writeState(state);location.reload();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-lifecycle]');if(!b)return;const action=b.dataset.lifecycle,id=b.dataset.player;if(action==='promote')promoteYouth(id);if(action==='retire')retirePlayer(id);if(action==='stay')stayPlayer(id);});
new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});
setTimeout(inject,300);
