import { loadWorld, generatePlayers } from './data.js';
import { loadGame, saveGame } from './storage.js';
import { advanceWeek, previewMatchday } from './simulation.js';

const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function seeded(seed){const x=Math.sin(seed*12.9898)*43758.5453;return x-Math.floor(x);}
function parseScore(result){const m=String(result).match(/(\d+)\s*[–-]\s*(\d+)/);return m?[+m[1],+m[2]]:[0,0];}
function strength(players){const p=(players||[]).filter(x=>(x.injuryWeeks||0)<=0).sort((a,b)=>(b.overall||0)-(a.overall||0)).slice(0,11);return p.length?p.reduce((s,x)=>s+(+x.overall||50),0)/p.length:50;}
function commonHalf(results){const scores=results.map(x=>parseScore(x.result));return [Math.min(...scores.map(x=>x[0])),Math.min(...scores.map(x=>x[1]))];}
function halfForFinal(result,seed){const [h,a]=parseScore(result);let hh=h?Math.floor(seeded(seed)*(h+1)):0;let aa=a?Math.floor(seeded(seed+17)*(a+1)):0;return[hh,aa];}
function minutes(count,start,end,seed){const out=[];for(let i=0;i<count;i++){let m=start+Math.floor(seeded(seed+i*29)*(end-start+1));while(out.includes(m))m=Math.min(end,m+1);out.push(m);}return out.sort((a,b)=>a-b);}
function buildReport(state,world,allPlayers,preview,half,decision='neutral'){
  const club=world.clubs.find(c=>c.id===state.clubId),opp=preview.opponent;
  const home=preview.home, [fh,fa]=parseScore(preview.result), [hh,ha]=half;
  const homeTeam=home?club?.name:(opp?.name||'League Opponent'), awayTeam=home?(opp?.name||'League Opponent'):club?.name;
  const homePower=home?strength(state.players):(+opp?.reputation||50), awayPower=home?(+opp?.reputation||50):strength(state.players);
  const gap=homePower-awayPower;
  const possessionBase=50+clamp(gap*.42,-11,11)+(home?2:-2);
  const homePoss=clamp(Math.round(possessionBase+seeded(preview.week*17)*6-3),36,64), awayPoss=100-homePoss;
  const baseShots=7+Math.round(seeded(preview.week*23)*5), awayShots=7+Math.round(seeded(preview.week*31)*5);
  const homeShots=clamp(baseShots+Math.round(gap/12)+(home?1:0),3,16), oppShots=clamp(awayShots-Math.round(gap/14)+(home?0:1),3,16);
  const homeSot=clamp(Math.min(homeShots,Math.round(homeShots*(.38+seeded(preview.week*41)*.22))),1,homeShots), oppSot=clamp(Math.min(oppShots,Math.round(oppShots*(.36+seeded(preview.week*43)*.22))),1,oppShots);
  const firstEvents=[];const secondEvents=[];
  const firstGoalCount=hh+ha, secondGoalCount=(fh-hh)+(fa-ha);
  const firstTimes=[...minutes(firstGoalCount,9,45,preview.week*101)];
  const secondTimes=[...minutes(secondGoalCount,48,90,preview.week*109)];
  const firstTeams=[];for(let i=0;i<hh;i++)firstTeams.push(homeTeam);for(let i=0;i<ha;i++)firstTeams.push(awayTeam);
  const secondTeams=[];for(let i=0;i<fh-hh;i++)secondTeams.push(homeTeam);for(let i=0;i<fa-ha;i++)secondTeams.push(awayTeam);
  firstTimes.forEach((m,i)=>firstEvents.push({minute:m,type:'goal',team:firstTeams[i]||homeTeam}));
  secondTimes.forEach((m,i)=>secondEvents.push({minute:m,type:'goal',team:secondTeams[i]||homeTeam}));
  const yellowCount=Math.floor(seeded(preview.week*53)*3),yellowTimes=minutes(yellowCount,22,88,preview.week*59);
  yellowTimes.forEach((m,i)=>secondEvents.push({minute:m,type:'card',team:i%2===0?homeTeam:awayTeam}));
  return {week:preview.week,home,homeTeam,awayTeam,opponent:opp?.name||'League Opponent',halfTime:`${hh}–${ha}`,final:preview.result,decision,homePossession:homePoss,awayPossession:awayPoss,homeShots,awayShots:oppShots,homeShotsOnTarget:homeSot,awayShotsOnTarget:oppSot,events:[...firstEvents,...secondEvents].sort((a,b)=>a.minute-b.minute)};
}
function applyReportToPlayers(report,before,after){const beforeBy=new Map((before.players||[]).map(p=>[p.id,p])),scorers=[];for(const p of after.players||[]){const old=beforeBy.get(p.id),delta=(p.goals||0)-(old?.goals||0);for(let i=0;i<delta;i++)scorers.push(p.name);}const goalEvents=report.events.filter(e=>e.type==='goal');goalEvents.forEach((e,i)=>{if(scorers[i])e.detail=`${scorers[i]} — ${e.team}`;});report.events=report.events.map(e=>e.type==='card'?{...e,detail:`Yellow card — ${e.team}`}:e);report.scorers=scorers;return report;}
function options(report){const [h,a]=parseScore(report.halfTime),clubIsHome=report.home,clubScore=clubIsHome?h:a,oppScore=clubIsHome?a:h;return clubScore>oppScore?[{id:'support',title:'Back the manager',text:'Keep the current approach. Confidence and balance are prioritised.',effect:'Balanced second half'},{id:'protect',title:'Protect the lead',text:'Urge control and game management. Lower risk, less attacking freedom.',effect:'Lower risk / lower attacking intent'},{id:'demand',title:'Push for more',text:'Demand that the team stays on the front foot. More attacking risk.',effect:'Higher attacking intent / higher risk'}]:[{id:'support',title:'Back the manager',text:'Keep confidence high and trust the football staff.',effect:'Balanced second half'},{id:'demand',title:'Demand a response',text:'Make it clear that the club expects a stronger second half.',effect:'Higher attacking intent / higher risk'},{id:'protect',title:'Urge control',text:'Stabilise the match and avoid turning frustration into further damage.',effect:'Lower risk / controlled approach'}];}
function overlay(html){let el=document.getElementById('matchday-fix-overlay');if(el)el.remove();el=document.createElement('div');el.id='matchday-fix-overlay';el.innerHTML=`<div style="position:fixed;inset:0;background:rgba(3,6,10,.86);backdrop-filter:blur(8px);z-index:99999;display:grid;place-items:center;padding:18px"><div style="width:min(900px,100%);max-height:92vh;overflow:auto;background:linear-gradient(145deg,#151b25,#0b0f15);border:1px solid rgba(214,178,82,.25);border-radius:16px;box-shadow:0 30px 80px rgba(0,0,0,.55);color:#f4f5f7;padding:22px">${html}</div></div>`;document.body.appendChild(el);return el;}
function close(){document.getElementById('matchday-fix-overlay')?.remove();}
function header(label,title,fixture){return `<div style="display:flex;justify-content:space-between;gap:16px;align-items:flex-start"><div><div style="font-size:11px;letter-spacing:.14em;text-transform:uppercase;opacity:.65">${esc(label)}</div><h2 style="margin:6px 0">${esc(title)}</h2><div style="opacity:.7">${fixture}</div></div></div>`;}
function fixtureLine(p){return `<div style="display:grid;grid-template-columns:1fr auto 1fr;gap:14px;align-items:center;margin:18px 0"><div style="text-align:right;font-weight:800">${esc(p.homeTeam)}</div><div style="font-size:30px;font-weight:900;letter-spacing:.05em">${p.halfTime}</div><div style="font-weight:800">${esc(p.awayTeam)}</div></div>`;}
function statGrid(r){return `<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px"><div style="padding:12px;border:1px solid rgba(255,255,255,.08);border-radius:10px"><small style="opacity:.6">Possession</small><strong style="display:block;margin-top:4px">${r.homePossession}% · ${r.awayPossession}%</strong></div><div style="padding:12px;border:1px solid rgba(255,255,255,.08);border-radius:10px"><small style="opacity:.6">Shots</small><strong style="display:block;margin-top:4px">${r.homeShots} · ${r.awayShots}</strong></div><div style="padding:12px;border:1px solid rgba(255,255,255,.08);border-radius:10px"><small style="opacity:.6">On target</small><strong style="display:block;margin-top:4px">${r.homeShotsOnTarget} · ${r.awayShotsOnTarget}</strong></div><div style="padding:12px;border:1px solid rgba(255,255,255,.08);border-radius:10px"><small style="opacity:.6">Phase</small><strong style="display:block;margin-top:4px">45 minutes</strong></div></div>`;}
function renderMatchday(state,world,allPlayers){const choices=['support','demand','protect'].map(d=>previewMatchday(state,world,d,allPlayers));const neutral=previewMatchday(state,world,'neutral',allPlayers),base=choices[0],half=commonHalf(choices.map(x=>x.result)),report=buildReport(state,world,allPlayers,base,half,'pending'),fixture=`${esc(report.homeTeam)} vs ${esc(report.awayTeam)}`;overlay(`${header(`Matchday · Week ${report.week}`,'Director’s Box',fixture)}<div style="margin-top:20px">${fixtureLine(report)}<div style="padding:14px 16px;border-radius:10px;background:rgba(214,178,82,.08);border:1px solid rgba(214,178,82,.16)"><strong>Half-time state is locked.</strong><div style="opacity:.75;margin-top:4px">The score, match stats and incidents shown here carry into the second half.</div></div>${statGrid(report)}<div style="margin-top:18px"><div style="font-size:12px;opacity:.6;text-transform:uppercase;letter-spacing:.12em">First-half incidents</div><div style="margin-top:8px">${report.events.filter(e=>e.minute<=45).length?report.events.filter(e=>e.minute<=45).map(e=>`<div style="padding:8px 0;border-bottom:1px solid rgba(255,255,255,.06)"><strong>${e.minute}'</strong> ${esc(e.detail||e.team)}</div>`).join(''):'<div style="padding:8px 0;opacity:.65">No goals or cards before the interval.</div>'}</div></div><div style="margin-top:20px"><div style="font-size:12px;opacity:.6;text-transform:uppercase;letter-spacing:.12em">Chairman intervention</div><div id="matchday-options" style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:10px">${options(report).map(o=>`<button data-fix-decision="${o.id}" style="padding:14px;text-align:left;border:1px solid rgba(255,255,255,.1);border-radius:10px;background:#111720;color:inherit;cursor:pointer"><strong>${esc(o.title)}</strong><span style="display:block;font-size:12px;opacity:.65;margin-top:6px">${esc(o.text)}</span><small style="display:block;margin-top:10px;color:#d6b252">${esc(o.effect)}</small></button>`).join('')}</div></div><div style="margin-top:18px;display:flex;justify-content:flex-end"><button data-fix-skip style="padding:11px 16px;border-radius:8px;border:1px solid rgba(255,255,255,.1);background:transparent;color:inherit;cursor:pointer">Skip this match instead</button></div></div>`);document.querySelectorAll('[data-fix-decision]').forEach(b=>b.onclick=()=>finishAttended(state,world,allPlayers,b.dataset.fixDecision,report));document.querySelector('[data-fix-skip]').onclick=()=>finishSkipped(state,world,allPlayers,neutral);}
function finishAttended(state,world,allPlayers,decision,report){const finalPreview=previewMatchday(state,world,decision,allPlayers),finalReport=buildReport(state,world,allPlayers,finalPreview,parseScore(report.halfTime),decision);state.pendingMatchdayDecision=decision;const next=advanceWeek(state,world,allPlayers);next.lastMatch=next.lastMatch||{};next.lastMatch.halfTime=finalReport.halfTime;next.lastMatch.finalResult=finalReport.final;next.lastMatch.homeScore=parseScore(finalReport.final)[0];next.lastMatch.awayScore=parseScore(finalReport.final)[1];next.lastMatch.report=finalReport;applyReportToPlayers(finalReport,state,next);saveGame(next);showResult(next,finalReport,'Match complete');}
function finishSkipped(state,world,allPlayers,preview){const half=halfForFinal(preview.result,preview.week*31),report=buildReport(state,world,allPlayers,preview,half,'neutral'),next=advanceWeek(state,world,allPlayers);next.lastMatch=next.lastMatch||{};next.lastMatch.halfTime=report.halfTime;next.lastMatch.finalResult=report.final;next.lastMatch.homeScore=parseScore(report.final)[0];next.lastMatch.awayScore=parseScore(report.final)[1];next.lastMatch.report=report;applyReportToPlayers(report,state,next);saveGame(next);showResult(next,report,'Match simulated');}
function showResult(state,report,title){const [fh,fa]=parseScore(report.final),timeline=report.events?.length?report.events.map(e=>`<div style="display:grid;grid-template-columns:48px 1fr;gap:10px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.06)"><strong>${e.minute}'</strong><span>${esc(e.detail||e.team)}</span></div>`).join(''):'<div style="opacity:.65;padding:10px 0">No recorded incidents.</div>';overlay(`${header(`Full-time · Week ${state.week}`,title,`${esc(report.homeTeam)} vs ${esc(report.awayTeam)}`)}<div style="display:grid;grid-template-columns:1fr auto 1fr;gap:14px;align-items:center;margin:22px 0"><div style="text-align:right;font-weight:800">${esc(report.homeTeam)}</div><div style="font-size:38px;font-weight:900">${fh}–${fa}</div><div style="font-weight:800">${esc(report.awayTeam)}</div></div><div style="padding:14px 16px;border-radius:10px;background:rgba(214,178,82,.08);border:1px solid rgba(214,178,82,.16)"><strong>Half-time ${esc(report.halfTime)} · Full-time ${fh}–${fa}</strong><div style="opacity:.72;margin-top:4px">The second-half score is calculated from the locked half-time state and your chairman intervention.</div></div><div style="margin-top:16px">${statGrid(report)}</div><div style="margin-top:18px"><div style="font-size:12px;opacity:.6;text-transform:uppercase;letter-spacing:.12em">Match timeline</div><div style="margin-top:8px">${timeline}</div></div><div style="display:flex;justify-content:flex-end;margin-top:20px"><button data-fix-close style="padding:11px 18px;border-radius:8px;border:1px solid rgba(214,178,82,.4);background:#b99645;color:#0b0f15;font-weight:800;cursor:pointer">Return to Chairman HQ</button></div>`);document.querySelector('[data-fix-close]').onclick=()=>{close();location.reload();};}
let busy=false;document.addEventListener('click',e=>{const b=e.target.closest?.('[data-action="advance"]');if(!b||busy)return;busy=true;e.preventDefault();e.stopImmediatePropagation();loadWorld().then(world=>{const state=loadGame();if(!state){busy=false;return;}const players=generatePlayers(world.clubs);renderMatchday(state,world,players);busy=false;}).catch(err=>{busy=false;console.error(err);alert('Matchday failed to open: '+err.message);});},true);
