import { loadWorld, generatePlayers } from './data.js';
import { loadGame, saveGame } from './storage.js';
import { advanceWeek, previewMatchday } from './simulation.js';

const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const parseScore=result=>{const m=String(result).match(/(\d+)\s*[–-]\s*(\d+)/);return m?[+m[1],+m[2]]:[0,0];};
const seeded=seed=>{const x=Math.sin(seed*12.9898)*43758.5453;return x-Math.floor(x);};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let busy=false;
let activeMatch=null;

function overlay(html){document.getElementById('matchday-fix-overlay')?.remove();const el=document.createElement('div');el.id='matchday-fix-overlay';el.innerHTML=`<div style="position:fixed;inset:0;background:rgba(3,6,10,.88);backdrop-filter:blur(8px);z-index:99999;display:grid;place-items:center;padding:18px;pointer-events:auto"><div style="width:min(900px,100%);max-height:92vh;overflow:auto;background:linear-gradient(145deg,#151b25,#0b0f15);border:1px solid rgba(214,178,82,.25);border-radius:16px;box-shadow:0 30px 80px rgba(0,0,0,.55);color:#f4f5f7;padding:22px">${html}</div></div>`;document.body.appendChild(el);return el;}
function close(){document.getElementById('matchday-fix-overlay')?.remove();activeMatch=null;}
function header(label,title,fixture){return `<div><div style="font-size:11px;letter-spacing:.14em;text-transform:uppercase;opacity:.65">${esc(label)}</div><h2 style="margin:6px 0">${esc(title)}</h2><div style="opacity:.7">${fixture}</div></div>`;}
function teams(state,world,p){const club=world.clubs.find(c=>c.id===state.clubId);return{homeTeam:p.home?club?.name:(p.opponent?.name||'League Opponent'),awayTeam:p.home?(p.opponent?.name||'League Opponent'):club?.name};}
function fixtureLine(p,score){return `<div style="display:grid;grid-template-columns:1fr auto 1fr;gap:14px;align-items:center;margin:18px 0"><div style="text-align:right;font-weight:800">${esc(p.homeTeam)}</div><div style="font-size:30px;font-weight:900;letter-spacing:.05em">${score}</div><div style="font-weight:800">${esc(p.awayTeam)}</div></div>`;}
function lockedResult(half,result){const [hh,ha]=parseScore(half),[fh,fa]=parseScore(result);return `${Math.max(hh,fh)}–${Math.max(ha,fa)}`;}
function commonHalf(previews){const scores=previews.map(p=>parseScore(p.halfTimeResult||p.result));return[ Math.min(...scores.map(s=>s[0])),Math.min(...scores.map(s=>s[1])) ];}
function statsFor(result,half,week){const [hg,ag]=parseScore(result),[hh,ha]=parseScore(half),seed=week*401+hg*17+ag*31;const homePoss=clamp(50+Math.round((seeded(seed)*2-1)*10),38,62),awayPoss=100-homePoss;const hs=clamp(Math.max(hg*2+3,7+Math.floor(seeded(seed+3)*8)),3,24),as=clamp(Math.max(ag*2+3,7+Math.floor(seeded(seed+5)*8)),3,24);const hot=clamp(Math.max(hg,Math.round(hs*(.34+seeded(seed+7)*.18))),hg,hs),aot=clamp(Math.max(ag,Math.round(as*(.34+seeded(seed+9)*.18))),ag,as);const firstRatio=.45+seeded(seed+11)*.12;const hhs=clamp(Math.max(hh+1,Math.round(hs*firstRatio)),hh,hs),ahs=clamp(Math.max(ha+1,Math.round(as*(firstRatio+.02))),ha,as);const hhot=clamp(Math.max(hh,Math.round(hot*firstRatio)),hh,hot),haot=clamp(Math.max(ha,Math.round(aot*firstRatio)),ha,aot);return{full:{homePossession:homePoss,awayPossession:awayPoss,homeShots:hs,awayShots:as,homeShotsOnTarget:hot,awayShotsOnTarget:aot,minutes:90},half:{homePossession:homePoss,awayPossession:awayPoss,homeShots:hhs,awayShots:ahs,homeShotsOnTarget:hhot,awayShotsOnTarget:haot,minutes:45}};}
function statGrid(r,label){return `<div style="margin-top:16px"><div style="font-size:12px;opacity:.6;text-transform:uppercase;letter-spacing:.12em;margin-bottom:8px">${label}</div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:10px"><div style="padding:12px;border:1px solid rgba(255,255,255,.08);border-radius:10px"><small style="opacity:.6">Possession</small><strong style="display:block;margin-top:4px">${r.homePossession}% · ${r.awayPossession}%</strong></div><div style="padding:12px;border:1px solid rgba(255,255,255,.08);border-radius:10px"><small style="opacity:.6">Shots</small><strong style="display:block;margin-top:4px">${r.homeShots} · ${r.awayShots}</strong></div><div style="padding:12px;border:1px solid rgba(255,255,255,.08);border-radius:10px"><small style="opacity:.6">On target</small><strong style="display:block;margin-top:4px">${r.homeShotsOnTarget} · ${r.awayShotsOnTarget}</strong></div><div style="padding:12px;border:1px solid rgba(255,255,255,.08);border-radius:10px"><small style="opacity:.6">Phase</small><strong style="display:block;margin-top:4px">${r.minutes} minutes</strong></div></div></div>`;}
function events(homeTeam,awayTeam,half,final){const [hh,ha]=parseScore(half),[fh,fa]=parseScore(final),out=[];const add=(count,start,end,homeCount,offset)=>{for(let i=0;i<count;i++){const minute=start+Math.floor(seeded((fh+fa+hh+ha)*91+offset+i*13)*(end-start+1));out.push({minute,team:i<homeCount?homeTeam:awayTeam});}};add(hh+ha,8,45,hh,11);add((fh-hh)+(fa-ha),48,90,fh-hh,37);return out.sort((a,b)=>a.minute-b.minute);}
function options(r){const [h,a]=parseScore(r.halfTime),club=r.home?h:a,opp=r.home?a:h;return club>opp?[['support','Back the manager','Keep confidence high and trust the football staff.','Balanced second half'],['protect','Protect the lead','Urge control and game management.','Lower risk / controlled approach'],['demand','Push for more','Demand that the team stays on the front foot.','Higher attacking intent / higher risk']]:[['support','Back the manager','Keep confidence high and trust the football staff.','Balanced second half'],['demand','Demand a response','Expect a stronger second half.','Higher attacking intent / higher risk'],['protect','Urge control','Stabilise the match and avoid further damage.','Lower risk / controlled approach']];}
function report(state,world,p,half,final,decision){const t=teams(state,world,p),s=statsFor(final,half,p.week);return{...p,...t,halfTime:half,final,decision,halfStats:s.half,stats:s.full,events:events(t.homeTeam,t.awayTeam,half,final)};}
function renderMatchday(state,world,players){const choices=['support','demand','protect'].map(d=>previewMatchday(state,world,d,players));const neutral=previewMatchday(state,world,'neutral',players),halfArr=commonHalf(choices),half=`${halfArr[0]}–${halfArr[1]}`,t=teams(state,world,neutral);activeMatch={state,world,players,week:neutral.week,home:neutral.home,opponent:neutral.opponent,halfTime:half,homeTeam:t.homeTeam,awayTeam:t.awayTeam};const base=report(state,world,neutral,half,neutral.result,'pending');overlay(`${header(`Matchday · Week ${base.week}`,'Director’s Box',`${esc(base.homeTeam)} vs ${esc(base.awayTeam)}`)}${fixtureLine(base,base.halfTime)}<div style="margin-top:10px;padding:14px 16px;border-radius:10px;background:rgba(214,178,82,.08);border:1px solid rgba(214,178,82,.16)"><strong>Half-time state is locked.</strong><div style="opacity:.75;margin-top:4px">The first-half score and statistics remain fixed while you make the chairman decision.</div></div>${statGrid(base.halfStats,'First-half stats')}<div style="margin-top:20px"><div style="font-size:12px;opacity:.6;text-transform:uppercase;letter-spacing:.12em">Chairman intervention</div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:10px">${options(base).map(o=>`<button type="button" data-fix-decision="${o[0]}" style="padding:14px;text-align:left;border:1px solid rgba(255,255,255,.1);border-radius:10px;background:#111720;color:inherit;cursor:pointer;touch-action:manipulation"><strong>${esc(o[1])}</strong><span style="display:block;font-size:12px;opacity:.65;margin-top:6px">${esc(o[2])}</span><small style="display:block;margin-top:10px;color:#d6b252">${esc(o[3])}</small></button>`).join('')}</div></div><div style="margin-top:18px;display:flex;justify-content:flex-end"><button type="button" data-fix-skip style="padding:11px 16px;border-radius:8px;border:1px solid rgba(255,255,255,.1);background:transparent;color:inherit;cursor:pointer;touch-action:manipulation">Skip this match instead</button></div>`);}
function showError(err){const box=document.querySelector('#matchday-fix-overlay > div > div');if(box)box.insertAdjacentHTML('beforeend',`<div style="margin-top:16px;padding:12px;border:1px solid rgba(220,80,80,.4);border-radius:10px;color:#ffb4b4">Matchday error: ${esc(err?.message||err)}</div>`);}
async function resolve(decision){if(!activeMatch)return;const{state,world,players,halfTime}=activeMatch;try{const p=previewMatchday(state,world,decision,players),final=lockedResult(halfTime,p.result);state.pendingMatchdayDecision=decision;state.pendingMatchdayResult=final;const next=advanceWeek(state,world,players),r=report(state,world,p,halfTime,final,decision);next.lastMatch=next.lastMatch||{};next.lastMatch.halfTime=halfTime;next.lastMatch.finalResult=final;next.lastMatch.homeScore=parseScore(final)[0];next.lastMatch.awayScore=parseScore(final)[1];next.lastMatch.report=r;saveGame(next);showResult(next,r,'Match complete');}catch(err){console.error(err);showError(err);}}
function showResult(state,r,title){const[fh,fa]=parseScore(r.final);overlay(`${header(`Full-time · Week ${state.week}`,title,`${esc(r.homeTeam)} vs ${esc(r.awayTeam)}`)}${fixtureLine(r,`${fh}–${fa}`)}<div style="margin-top:10px;padding:14px 16px;border-radius:10px;background:rgba(214,178,82,.08);border:1px solid rgba(214,178,82,.16)"><strong>Half-time ${esc(r.halfTime)} · Full-time ${fh}–${fa}</strong><div style="opacity:.72;margin-top:4px">The displayed score, timeline and statistics are derived from the same match result.</div></div>${statGrid(r.stats,'Full-time stats')}<div style="margin-top:18px"><div style="font-size:12px;opacity:.6;text-transform:uppercase;letter-spacing:.12em">Match timeline</div>${r.events.length?r.events.map(e=>`<div style="padding:8px 0;border-bottom:1px solid rgba(255,255,255,.06)"><strong>${e.minute}'</strong> ${esc(e.team)} — Goal</div>`).join(''):'<div style="padding:8px 0;opacity:.65">No goals recorded.</div>'}</div><div style="display:flex;justify-content:flex-end;margin-top:20px"><button type="button" data-fix-close style="padding:11px 18px;border-radius:8px;border:1px solid rgba(214,178,82,.4);background:#b99645;color:#0b0f15;font-weight:800;cursor:pointer;touch-action:manipulation">Return to Chairman HQ</button></div>`);}

document.addEventListener('click',async e=>{const decision=e.target.closest?.('[data-fix-decision]'),skip=e.target.closest?.('[data-fix-skip]'),closeBtn=e.target.closest?.('[data-fix-close]');if(closeBtn){e.preventDefault();e.stopImmediatePropagation();close();location.reload();return;}if(!decision&&!skip)return;e.preventDefault();e.stopImmediatePropagation();if(busy)return;busy=true;document.querySelectorAll('[data-fix-decision],[data-fix-skip]').forEach(b=>b.disabled=true);try{await resolve(decision?decision.dataset.fixDecision:'neutral');}catch(err){showError(err);}finally{busy=false;}},true);
document.addEventListener('click',async e=>{const b=e.target.closest?.('[data-action="advance"]');if(!b||busy)return;busy=true;e.preventDefault();e.stopImmediatePropagation();try{const world=await loadWorld(),state=loadGame();if(!state)throw new Error('Game state could not be loaded.');const players=generatePlayers(world.clubs);renderMatchday(state,world,players);}catch(err){console.error(err);alert('Matchday failed to open: '+err.message);}finally{busy=false;}},true);
