import { loadWorld, generatePlayers } from './data.js';
import { loadGame } from './storage.js';
import { previewMatchday } from './simulation.js?prematch=94';
import { managerSelection } from './manager-selection.js?prematch=94';

let opening=false;
let allowAdvanceOnce=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pos=p=>p?.position||'—';
const playerRow=(p,i)=>`<div style="display:grid;grid-template-columns:28px 1fr 54px 54px;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid rgba(255,255,255,.06)"><span style="opacity:.45">${i+1}</span><strong>${esc(p.name)}</strong><span style="opacity:.7;text-align:center">${esc(pos(p))}</span><span style="text-align:right;font-weight:800">${Number(p.overall)||'—'}</span></div>`;
function showPreMatch(state,world,players){
  const p=previewMatchday(state,world,'neutral',players),club=world.clubs.find(c=>c.id===state.clubId),home=p.home?(club?.name||'Home'):(p.opponent?.name||'League Opponent'),away=p.home?(p.opponent?.name||'League Opponent'):(club?.name||'Away'),selection=managerSelection(state),manager=state.manager||{},managerName=manager.name||'Club Manager';
  document.getElementById('prematch-gate')?.remove();
  const el=document.createElement('div');el.id='prematch-gate';
  el.innerHTML=`<div style="position:fixed;inset:0;background:rgba(3,6,10,.9);backdrop-filter:blur(8px);z-index:99998;display:grid;place-items:center;padding:18px"><div style="width:min(920px,100%);max-height:92vh;overflow:auto;background:linear-gradient(145deg,#151b25,#0b0f15);border:1px solid rgba(214,178,82,.25);border-radius:16px;box-shadow:0 30px 80px rgba(0,0,0,.55);color:#f4f5f7;padding:22px"><div style="font-size:11px;letter-spacing:.14em;text-transform:uppercase;opacity:.65">Matchday · Week ${p.week}</div><h2 style="margin:6px 0">Pre-match</h2><div style="display:grid;grid-template-columns:1fr auto 1fr;gap:14px;align-items:center;margin:26px 0"><div style="text-align:right;font-weight:900;font-size:18px">${esc(home)}</div><div style="font-size:24px;font-weight:900;opacity:.5">VS</div><div style="font-weight:900;font-size:18px">${esc(away)}</div></div><div style="padding:16px;border-radius:10px;background:rgba(214,178,82,.08);border:1px solid rgba(214,178,82,.16)"><strong>Manager's matchday preparation</strong><div style="opacity:.75;margin-top:6px">${esc(managerName)} has selected the XI and bench using ability, fitness, form, morale, fatigue and availability. The manager controls substitutions during the match.</div></div><div style="margin-top:16px;padding:14px;border:1px solid rgba(255,255,255,.08);border-radius:10px"><div style="font-size:12px;opacity:.6;text-transform:uppercase;letter-spacing:.1em">Starting XI · Manager selection</div><div style="display:grid;grid-template-columns:28px 1fr 54px 54px;gap:8px;padding:8px 0;font-size:11px;opacity:.5;text-transform:uppercase"><span></span><span>Player</span><span style="text-align:center">POS</span><span style="text-align:right">OVR</span></div>${selection.selected.map(playerRow).join('')}</div><div style="margin-top:12px;padding:14px;border:1px solid rgba(255,255,255,.08);border-radius:10px"><div style="font-size:12px;opacity:.6;text-transform:uppercase;letter-spacing:.1em">Bench · 7 substitutes · maximum 5 used</div>${selection.bench.map(playerRow).join('')}</div><button type="button" data-prematch-start style="width:100%;margin-top:20px;padding:16px;border:1px solid rgba(214,178,82,.45);border-radius:10px;background:#b99645;color:#0b0f15;font-weight:900;font-size:16px;cursor:pointer;touch-action:manipulation">Start Match</button></div></div>`;
  document.body.appendChild(el);
}
document.addEventListener('click',async e=>{
  const start=e.target.closest?.('[data-prematch-start]'),advance=e.target.closest?.('[data-action="advance"]');
  if(advance&&!allowAdvanceOnce){e.preventDefault();e.stopImmediatePropagation();if(opening)return;opening=true;try{const world=await loadWorld(),state=loadGame();if(!state)throw new Error('Game state could not be loaded.');const players=generatePlayers(world.clubs);showPreMatch(state,world,players);}catch(err){console.error(err);alert('Pre-match failed to open: '+err.message);}finally{opening=false;}return;}
  if(start){e.preventDefault();e.stopImmediatePropagation();allowAdvanceOnce=true;document.getElementById('prematch-gate')?.remove();const b=document.querySelector('[data-action="advance"]');if(b)b.click();queueMicrotask(()=>{allowAdvanceOnce=false;});}
},true);
