const SAVE_KEY='the-chairman-save-v1';
let sortKey='overall';
let sortDir=-1;
let busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>`£${Math.round(Number(n)||0).toLocaleString('en-GB')}`;
const num=n=>Number.isFinite(Number(n))?Number(n):0;
const pct=(won,total)=>total?Math.round((won/total)*100):0;
function readState(){try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null');}catch{return null;}}
function valueFor(p,key){if(key==='tacklePct')return pct(num(p.tacklesWon),num(p.tackles));if(key==='value'||key==='wage')return num(p[key]);if(key==='rating'||key==='avgRating')return num(p.avgRating);return num(p[key]);}
function formatCell(p,key){const v=valueFor(p,key);if(key==='value')return money(v);if(key==='wage')return `${money(v)}/wk`;if(key==='form'||key==='fitness')return `${Math.round(v)}%`;if(key==='rating')return v?v.toFixed(1):'—';if(key==='tacklePct')return `${v}%`;return key==='name'?esc(p.name):String(v||0);}
function headers(){return [['name','Player'],['position','Pos'],['age','Age'],['overall','OVR'],['potential','Pot'],['appearances','Apps'],['minutes','Min'],['goals','G'],['assists','A'],['keyPasses','KP'],['cleanSheets','CS'],['tackles','Tkl'],['tacklePct','Tkl%'],['interceptions','Int'],['clearances','Clr'],['saves','Sv'],['avgRating','Avg'],['form','Form'],['fitness','Fit'],['value','Value'],['wage','Wage']];}
function row(p){return `<tr>${headers().map(([key])=>key==='name'?`<td data-sort="${esc(p.name)}"><strong>${esc(p.name)}</strong><small style="display:block">${esc(p.personality||'Balanced')} · ${p.contractYears||0} yrs</small></td>`:`<td data-sort="${valueFor(p,key)}">${formatCell(p,key)}</td>`).join('')}<td><button class="btn" data-action="sellPlayer" data-player="${esc(p.id)}">Consider sale</button></td></tr>`;}
function sortRows(table){const tbody=table.tBodies[0];if(!tbody)return;const hs=headers(),index=hs.findIndex(x=>x[0]===sortKey);[...tbody.rows].sort((a,b)=>{const av=a.cells[index]?.dataset.sort??'',bv=b.cells[index]?.dataset.sort??'',an=Number(av),bn=Number(bv);if(Number.isFinite(an)&&Number.isFinite(bn))return(an-bn)*sortDir;return String(av).localeCompare(String(bv))*sortDir;}).forEach(r=>tbody.appendChild(r));}
function enhance(){if(busy)return;const heading=[...document.querySelectorAll('#view h2')].find(x=>x.textContent.trim()==='First-team performance');if(!heading)return;const section=heading.closest('section'),table=section?.querySelector('table');if(!table||table.dataset.squadEnhanced==='1')return;const state=readState(),players=Array.isArray(state?.players)?state.players:[];if(!players.length)return;busy=true;const hs=headers();table.classList.add('squad-table');table.dataset.squadEnhanced='1';table.innerHTML=`<thead><tr>${hs.map(([key,label])=>`<th scope="col" data-squad-sort="${key}" title="Sort by ${label}">${label}</th>`).join('')}<th>Chairman</th></tr></thead><tbody>${players.map(row).join('')}</tbody>`;table.querySelectorAll('[data-squad-sort]').forEach(th=>th.addEventListener('click',()=>{const key=th.dataset.squadSort;if(sortKey===key)sortDir*=-1;else{sortKey=key;sortDir=['name','position'].includes(key)?1:-1;}table.querySelectorAll('[data-squad-sort]').forEach(x=>x.classList.toggle('sorted',x===th));sortRows(table);}));sortRows(table);busy=false;}
const style=document.createElement('style');style.textContent='.table-wrap{overflow-x:auto;-webkit-overflow-scrolling:touch}.squad-table{min-width:1480px;border-collapse:separate;border-spacing:0;font-size:12px}.squad-table th{position:sticky;top:0;z-index:2;white-space:nowrap;cursor:pointer;user-select:none;padding:12px 10px}.squad-table th:hover,.squad-table th.sorted{color:var(--gold,#d4af37)}.squad-table td{white-space:nowrap;padding:10px;border-bottom:1px solid var(--line,#242b36)}.squad-table td:first-child{min-width:190px;white-space:normal}@media(max-width:700px){.squad-table{min-width:1480px}.squad-table th,.squad-table td{padding:9px 8px}}';document.head.appendChild(style);
new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});
setTimeout(enhance,100);
