const SAVE_KEY='the-chairman-save-v1';
let sortKey='position';
let sortDir=1;
let busy=false;
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const money=n=>`£${Math.round(Number(n)||0).toLocaleString('en-GB')}`;
const num=n=>Number.isFinite(Number(n))?Number(n):0;
const pct=(won,total)=>total?Math.round((won/total)*100):0;
const POS_ORDER={GK:10,RB:20,RCB:30,CB:40,LCB:50,LB:60,DM:70,RM:80,RCM:90,CM:100,LCM:110,LM:120,AM:130,RW:140,LW:150,ST:160};
const SORT_LABELS={name:'Player',position:'Position',age:'Age',overall:'Overall',potential:'Potential',appearances:'Appearances',minutes:'Minutes',goals:'Goals',assists:'Assists',keyPasses:'Key passes',cleanSheets:'Clean sheets',tackles:'Tackles',tacklePct:'Tackle %',interceptions:'Interceptions',clearances:'Clearances',saves:'Saves',avgRating:'Average rating',form:'Form',fitness:'Fitness',value:'Value',wage:'Wage',clubYears:'Years at Club'};
function readState(){try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'null');}catch{return null;}}
function writeState(state){localStorage.setItem(SAVE_KEY,JSON.stringify(state));}
function valueFor(p,key){if(key==='position')return POS_ORDER[p.position]??999;if(key==='tacklePct')return pct(num(p.tacklesWon),num(p.tackles));if(key==='value'||key==='wage')return num(p[key]);if(key==='rating'||key==='avgRating')return num(p.avgRating);if(key==='clubYears')return num(p.clubYears||p.yearsAtClub);return num(p[key]);}
function formatCell(p,key){if(key==='position')return esc(p.position||'—');const v=valueFor(p,key);if(key==='value')return money(v);if(key==='wage')return `${money(v)}/wk`;if(key==='form'||key==='fitness')return `${Math.round(v)}%`;if(key==='rating'||key==='avgRating')return v?v.toFixed(1):'—';if(key==='tacklePct')return `${v}%`;return key==='name'?esc(p.name):String(v||0);}
function headers(){return [['name','Player'],['position','POS'],['age','AGE'],['overall','OVR'],['potential','POT'],['appearances','APP'],['minutes','MIN'],['goals','G'],['assists','A'],['keyPasses','KP'],['cleanSheets','CS'],['tackles','TKL'],['tacklePct','TKL%'],['interceptions','INT'],['clearances','CLR'],['saves','SAV'],['avgRating','AVG'],['form','FORM'],['fitness','FIT'],['value','VALUE'],['wage','WAGE'],['clubYears','YEARS']];}
function row(p){return `<tr>${headers().map(([key])=>key==='name'?`<td data-sort="${esc(p.name)}"><strong>${esc(p.name)}</strong><small style="display:block">${esc(p.personality||'Balanced')} · ${p.contractYears||0} yrs</small></td>`:key==='clubYears'?`<td data-sort="${num(p.clubYears||p.yearsAtClub)}">${num(p.clubYears||p.yearsAtClub)}</td>`:`<td data-sort="${valueFor(p,key)}">${formatCell(p,key)}</td>`).join('')}<td><div class="squad-actions"><button class="btn" data-squad-action="demote" data-player="${esc(p.id)}">Youth</button><button class="btn" data-action="sellPlayer" data-player="${esc(p.id)}">Sale</button></div></td></tr>`;}
function sortRows(table){const tbody=table.tBodies[0];if(!tbody)return;const hs=headers(),index=hs.findIndex(x=>x[0]===sortKey);[...tbody.rows].sort((a,b)=>{const av=a.cells[index]?.dataset.sort??'',bv=b.cells[index]?.dataset.sort??'',an=Number(av),bn=Number(bv);if(Number.isFinite(an)&&Number.isFinite(bn))return(an-bn)*sortDir;return String(av).localeCompare(String(bv))*sortDir;}).forEach(r=>tbody.appendChild(r));}
function youthActions(state){return [...(state.youthSquad||[])].map(p=>`<button class="btn" data-squad-action="promote" data-player="${esc(p.id)}" ${Number(p.age)<16?'disabled':''}>${Number(p.age)<16?'15-year-old — not eligible':'Promote to first team'}</button>`).join('');}
function pendingRetirementMarkup(state){const pending=Array.isArray(state.pendingRetirements)?state.pendingRetirements:[];if(!pending.length)return '';return `<section class="card card-pad" style="margin-top:18px;border-color:rgba(212,175,55,.35)"><div class="section-title"><h2>Retirement decisions</h2><span>${pending.length} awaiting your decision</span></div>${pending.map(p=>`<div class="list-row"><div><strong>${esc(p.name)}</strong><small>${esc(p.position)} · Age ${p.age} · OVR ${p.overall} · Retirement stage reached</small></div><div class="actions"><button class="btn" data-squad-action="extend" data-player="${esc(p.id)}">Persuade to stay</button><button class="btn btn-primary" data-squad-action="retire" data-player="${esc(p.id)}">Confirm retirement</button></div></div>`).join('')}</section>`;}
function promote(state,id){const index=(state.youthSquad||[]).findIndex(p=>p.id===id);if(index<0)return;const player=state.youthSquad[index];if(Number(player.age)<16){alert('15-year-old players cannot be promoted to the first team.');return;}if((state.players||[]).length>=25){alert('The first-team squad is at its 25-player capacity.');return;}state.youthSquad.splice(index,1);player.pathway='first-team';state.players.push(player);state.news.unshift({week:state.week,title:`Youth promotion: ${player.name}`,text:`The manager has promoted ${player.name} to the first team at age ${player.age}.`});state.inbox.unshift({id:Date.now(),type:'SQUAD',title:`Youth player promoted: ${player.name}`,text:`${player.name} has joined the first-team squad.`,unread:true});writeState(state);location.reload();}
function demote(state,id){const index=(state.players||[]).findIndex(p=>p.id===id);if(index<0)return;if((state.youthSquad||[]).length>=6){alert('The youth squad is full at 6 players. Promote a youth player first to create space.');return;}const player=state.players[index];state.players.splice(index,1);player.pathway='youth';state.youthSquad.push(player);state.news.unshift({week:state.week,title:`Player moved to youth pathway: ${player.name}`,text:`${player.name} has been moved out of the first team for development.`});writeState(state);location.reload();}
function newYouth(state,seed){const positions=['GK','RB','CB','LB','DM','CM','AM','RW','LW','ST'];const r=n=>{const x=Math.sin(seed*n*12.9898)*43758.5453;return x-Math.floor(x);};const potential=68+Math.floor(r(1)*25),overall=Math.max(48,Math.min(62,potential-Math.floor(8+r(2)*10))),age=15+Math.floor(r(3)*3),first=['Leo','Milo','Noah','Elias','Ruben','Theo','Luca','Kai','Oscar','Jonas'][Math.floor(r(4)*10)],last=['Vale','Mercer','Santos','Keller','Rossi','Bauer','Navarro','Mills','Hart','Meyer'][Math.floor(r(5)*10)];return{id:`${state.clubId}-youth-ret-${state.week}-${seed}`,clubId:state.clubId,name:`${first} ${last}`,age,position:positions[Math.floor(r(6)*positions.length)],overall,potential,value:25000,wage:Math.round(overall*overall*.9+potential*12),morale:70,form:62,fitness:85,contractYears:3,clubYears:0,developmentProgress:overall,development:0,recentRatings:[],personality:'Ambitious',pathway:'youth'};}
function extendRetirement(state,id){const player=state.players.find(p=>p.id===id);if(!player)return;player.retirementPending=false;player.retirementExtensionYears=(player.retirementExtensionYears||0)+1;player.contractYears=Math.max(1,(player.contractYears||0)+1);state.pendingRetirements=(state.pendingRetirements||[]).filter(x=>x.id!==id);state.news.unshift({week:state.week,title:`Retirement delayed: ${player.name}`,text:`You persuaded ${player.name} to remain for another season.`});writeState(state);location.reload();}
function retire(state,id){const index=state.players.findIndex(p=>p.id===id);if(index<0)return;const player=state.players[index];state.players.splice(index,1);player.retirementPending=false;player.retiredWeek=state.week;state.retiredPlayers=[...(state.retiredPlayers||[]),player].slice(-30);state.pendingRetirements=(state.pendingRetirements||[]).filter(x=>x.id!==id);let replacement=null;if((state.youthSquad||[]).length<6)replacement=newYouth(state,state.week+state.retiredPlayers.length);if(replacement)state.youthSquad.push(replacement);else state.pendingYouthIntake=(state.pendingYouthIntake||0)+1;state.news.unshift({week:state.week,title:`Retirement confirmed: ${player.name}`,text:replacement?`${player.name} retires and a new youth prospect has entered the academy.`:`${player.name} retires. The academy is full, so the replacement youth intake is waiting for pathway space.`});state.inbox.unshift({id:Date.now(),type:'RETIREMENT',title:`Retirement confirmed: ${player.name}`,text:replacement?`A new youth prospect has entered the academy.`:`Youth squad is full (6/6); promote a youth player to create intake space.`,unread:true});writeState(state);location.reload();}
function handleSquadAction(action,id){const state=readState();if(!state)return;if(action==='promote')promote(state,id);if(action==='demote')demote(state,id);if(action==='extend')extendRetirement(state,id);if(action==='retire')retire(state,id);}
function enhance(){if(busy)return;const heading=[...document.querySelectorAll('#view h2')].find(x=>x.textContent.trim()==='First-team performance');if(!heading)return;const section=heading.closest('section'),table=section?.querySelector('table');if(!table)return;const state=readState(),players=Array.isArray(state?.players)?state.players:[];if(!players.length)return;busy=true;const hs=headers();table.classList.add('squad-table');table.innerHTML=`<thead><tr>${hs.map(([key,label])=>`<th scope="col" data-squad-sort="${key}" title="Sort ${label} · ${SORT_LABELS[key]}"><span class="sort-label">Sort ${label}</span><span class="sort-help">${SORT_LABELS[key]}</span></th>`).join('')}<th>CHAIRMAN</th></tr></thead><tbody>${players.map(row).join('')}</tbody>`;table.querySelectorAll('[data-squad-sort]').forEach(th=>th.addEventListener('click',()=>{const key=th.dataset.squadSort;if(sortKey===key)sortDir*=-1;else{sortKey=key;sortDir=key==='position'||key==='name'||key==='clubYears'?1:-1;}table.querySelectorAll('[data-squad-sort]').forEach(x=>x.classList.toggle('sorted',x===th));sortRows(table);}));sortRows(table);section.querySelectorAll('[data-squad-action]').forEach(b=>b.onclick=()=>handleSquadAction(b.dataset.squadAction,b.dataset.player));
const youthSection=[...document.querySelectorAll('#view h2')].find(x=>x.textContent.trim()==='Youth pathway')?.closest('section');if(youthSection){youthSection.querySelectorAll('.card').forEach(card=>{const name=card.querySelector('h3')?.textContent?.trim(),player=(state.youthSquad||[]).find(p=>p.name===name);if(player&&!card.querySelector('[data-squad-action="promote"]')){const actions=document.createElement('div');actions.className='actions';actions.style.marginTop='12px';actions.innerHTML=`<button class="btn ${Number(player.age)>=16?'btn-primary':''}" data-squad-action="promote" data-player="${esc(player.id)}" ${Number(player.age)<16?'disabled':''}>${Number(player.age)<16?'Not eligible at 15':'Promote to first team'}</button>`;card.appendChild(actions);actions.querySelector('button').onclick=()=>handleSquadAction('promote',player.id);}});const cap=document.createElement('div');cap.className='notice';cap.style.marginBottom='12px';cap.textContent=`Youth squad capacity: ${Math.min(6,(state.youthSquad||[]).length)}/6 · Players aged 15 cannot be promoted.`;youthSection.insertBefore(cap,youthSection.querySelector('.grid'));}
const lifecycle=[...document.querySelectorAll('#view h2')].find(x=>x.textContent.trim()==='Career lifecycle')?.closest('section');if(lifecycle&&!document.querySelector('#retirement-decisions')){const holder=document.createElement('div');holder.id='retirement-decisions';holder.innerHTML=pendingRetirementMarkup(state);lifecycle.after(holder);holder.querySelectorAll('[data-squad-action]').forEach(b=>b.onclick=()=>handleSquadAction(b.dataset.squadAction,b.dataset.player));}
busy=false;}
const style=document.createElement('style');style.textContent='.table-wrap{overflow-x:auto;-webkit-overflow-scrolling:touch}.squad-table{min-width:1900px;border-collapse:separate;border-spacing:0;font-size:12px}.squad-table th{position:sticky;top:0;z-index:2;white-space:nowrap;cursor:pointer;user-select:none;padding:10px 9px;text-align:left}.squad-table th:hover,.squad-table th.sorted{color:var(--gold,#d4af37)}.squad-table .sort-label{display:block;font-weight:800}.squad-table .sort-help{display:block;font-size:9px;font-weight:500;opacity:.58;margin-top:2px}.squad-table td{white-space:nowrap;padding:10px;border-bottom:1px solid var(--line,#242b36)}.squad-table td:first-child{min-width:190px;white-space:normal}.squad-actions{display:flex;gap:6px}.squad-actions .btn{padding:6px 8px}@media(max-width:700px){.squad-table{min-width:1900px}.squad-table th,.squad-table td{padding:9px 8px}}';document.head.appendChild(style);
new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});
setTimeout(enhance,100);
