const firstNames=['Adrian','Marco','Luca','Mateo','Jonas','Felix','Nico','Theo','Ruben','Milan','Oscar','Elias','Hugo','Leon','Arthur','Daniel','Sandro','Victor','Emil','Alex'];
const lastNames=['Varela','Mercer','Santos','Keller','Rossi','Bauer','Navarro','Duarte','Mills','Hart','Vega','Costa','Bennett','Fischer','Moreau','Silva','Reed','Laurent','King','Meyer'];
const nationalities=[['England','ENG'],['Spain','ESP'],['Germany','GER'],['Italy','ITA'],['France','FRA'],['Portugal','POR'],['Netherlands','NED'],['Belgium','BEL'],['Denmark','DEN'],['Croatia','CRO'],['Sweden','SWE'],['Norway','NOR'],['Ireland','IRL'],['Scotland','SCO']];
const formations=['4-4-2','4-3-3 DM','4-5-1 flat','4-1-4-1','4-4-1-1','5-3-1-2'];
const roles=['manager','coach','youthCoach','commercialDirector','physio','scout'];
const hash=n=>{const x=Math.sin(n*12.9898)*43758.5453;return x-Math.floor(x);};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function identity(seed){return{name:`${firstNames[(seed*7)%firstNames.length]} ${lastNames[(seed*11)%lastNames.length]}`,nationality:nationalities[(seed*5)%nationalities.length][0],nationalityCode:nationalities[(seed*5)%nationalities.length][1]};}
function baseStaff(id,role,seed,clubId=null){const idn=identity(seed);const age=role==='manager'?28+Math.floor(hash(seed+2)*37):24+Math.floor(hash(seed+2)*38);const experience=clamp(Math.round(18+hash(seed+4)*68+(age-25)*.45),10,96);const reputation=clamp(Math.round(22+experience*.72+hash(seed+6)*18),20,96);const wage=Math.round((role==='manager'?1800:role==='commercialDirector'?1250:role==='coach'?1100:role==='scout'?900:role==='physio'?850:700)*(0.65+reputation/100));return{id,role,...idn,age,reputation,experience,wage,contractYears:1+Math.floor(hash(seed+8)*4),clubId,status:clubId?'employed':'freeAgent',personality:['Leader','Professional','Ambitious','Loyal','Demanding','Calm'][seed%6],career:{clubs:clubId?1:0,seasons:0,trophies:0,promotions:0}};}
function manager(seed,clubId=null){const s=baseStaff(`mgr-${seed}`,'manager',seed,clubId);const preferred=formations[seed%formations.length];const secondary=formations[(seed+2+Math.floor(hash(seed+30)*3))%formations.length];return{...s,preferredFormation:preferred,secondaryFormation:secondary,playingStyle:['Balanced','Possession','Direct','High Press','Counter Attack','Pragmatic'][seed%6],managerRating:clamp(Math.round(s.reputation*.55+s.experience*.45),20,96),potential:clamp(Math.round(s.reputation+hash(seed+31)*20-6),s.reputation,99),managerPerformance:60,managerConfidence:clubId?70:50,relationship:clubId?60:50,career:{...s.career,majorTrophies:0,leagueTitles:0}};}
function specialist(id,role,seed,clubId=null){const s=baseStaff(id,role,seed,clubId);if(role==='scout')return{...s,scoutStars:1+Math.min(2,Math.floor(hash(seed+40)*3)),scoutingRating:clamp(Math.round(s.reputation*.6+s.experience*.4),20,96)};if(role==='physio')return{...s,medicalRating:clamp(Math.round(s.reputation*.55+s.experience*.45),20,96)};if(role==='commercialDirector')return{...s,commercialRating:clamp(Math.round(s.reputation*.55+s.experience*.45),20,96)};if(role==='youthCoach')return{...s,youthDevelopmentRating:clamp(Math.round(s.reputation*.5+s.experience*.5),20,96)};return{...s,coachingRating:clamp(Math.round(s.reputation*.5+s.experience*.5),20,96)};}
export function generateStaff(clubs){const staff=[];clubs.forEach((club,ci)=>{const base=ci*100;staff.push(manager(base+1,club.id));staff.push(specialist(`coach-${base+2}`,'coach',base+2,club.id));staff.push(specialist(`youth-${base+3}`,'youthCoach',base+3,club.id));staff.push(specialist(`commercial-${base+4}`,'commercialDirector',base+4,club.id));staff.push(specialist(`physio-${base+5}`,'physio',base+5,club.id));staff.push(specialist(`scout-${base+6}`,'scout',base+6,club.id));});let seed=10000;for(const role of roles){for(let i=0;i<100;i++,seed++){staff.push(role==='manager'?manager(seed):specialist(`${role}-${seed}`,role,seed));}}return staff;}
export function staffForClub(staff,clubId){return staff.filter(s=>s.clubId===clubId);}
export function managerForClub(staff,clubId){return staff.find(s=>s.role==='manager'&&s.clubId===clubId)||null;}
export function freeStaff(staff){return staff.filter(s=>s.status==='freeAgent');}
